### PR TITLE
Allow alternative VCS driver to be specified (e.g., for gitlab)

### PR DESCRIPTION
**Pull request by bradjones1**
Composer allows for alternative VCS drivers; satis could easily support this in the `add` command. This PR adds an optional option to this command, defaulting to the current `vcs` value, for users to take advantage of this feature.

https://getcomposer.org/doc/05-repositories.md#git-alternatives

Refs https://github.com/composer/satis/issues/419

### CODE REVIEW

**Comment by bradjones1** [comment]
@alcohol You are correct. Thanks.

**Comment by bradjones1** [comment]
@alcohol In setting up our satis workflow, I did actually run into a case where this may be necessary; in our case, we do a `satis add` (actually called from a symfony controller) however the only access for Satis to GitLab is via the token.

When satis adds the repository, the type is the default, `vcs`, and the git driver attempts to do the clone, hanging us. I would need to specify `gitlab` at runtime to force this driver to fetch the info and validate the repository.

I am open to other workflows (perhaps the add command does as advertised and just adjusts the json, instead of doing any validation?) but for the moment this is necessary for us to get the repo into `satis.json`. Once it's there, the driver is properly selected.

**Comment by bradjones1** [comment]
So this isn't necessary however I wonder if there is room for some documentation improvements either here or on composer core. Basically, in `::isRepositoryValid()`, a config is yielded from `Factory::createConfig()`, which does not parse any config options from `satis.json` but it will bring them in from `COMPOSER_HOME/config.json`. So any gitlab options must be in the config, even though on other operations satis will use the values in `satis.json`.

**Comment by alcohol** [comment]
I cannot tell if `isRepositoryValid` is part of Composer or part of Satis, I'd have to check. If it is the former there isn't much we can do about this because Composer is not aware of Satis. If however if it is part of Satis, we could probably make adjustments there to allow for some sort of merge behaviour of configurations.

**Comment by bradjones1** [comment]
@alcohol https://github.com/composer/satis/blob/7ab2986770b2106fc67d754bf4f3144065e8ff1b/src/Console/Command/AddCommand.php#L115

Thanks!

**Comment by alcohol** [comment]
Is this change still desired?

**Comment by bradjones1** [comment]
It is not a blocker for us as we've worked around it, but yes I think implementing a consistent behavior (re: the items raised in https://github.com/composer/satis/pull/527#issuecomment-469922768) would be good to do in Satis.

**Pull request merged**
