### PR TITLE
include error details about validation errors

### PR DESCRIPTION
**Pull request by glensc**
see https://github.com/composer/satis/pull/271#issuecomment-169672818
and https://github.com/composer/satis/pull/271#issuecomment-169676702

### CODE REVIEW

**Comment by glensc** [comment]
should it be formatted somehow better? currently result is:

````
➔ ./bin/satis build libs.json 
homepage : The property homepage is required

                                                                
  [Composer\Json\JsonValidationException]                       
  The json config file does not match the expected JSON schema  
                                                                

build [--repository-url [REPOSITORY-URL]] [--no-html-output] [--skip-errors] [--] [<file>] [<output-dir>] [<packages>]...
```

**Comment by glensc** [comment]
@stof

**Comment by glensc** [comment]
err ping?

**Comment by till** [comment]
:+1: looks simple enough :)

**Comment by alcohol** [comment]
This no longer catches the `UnexpectedValueException` and `ParsingException` that `check()` can also throw. Please add additional catch statements.

**Comment by glensc** [comment]
that would be a lot duplication, maybe catch \Exception and do `instanceof` check instead?

```diff
@@ -132,6 +131,16 @@ protected function execute(InputInterface $input, OutputInterface $output)
                 throw $e;
             }
             $output->writeln(sprintf('<warning>%s: %s</warning>', get_class($e), $e->getMessage()));
+        } catch (ParsingException $e) {
+            if (!$skipErrors) {
+                throw $e;
+            }
+            $output->writeln(sprintf('<warning>%s: %s</warning>', get_class($e), $e->getMessage()));
+        } catch (\UnexpectedValueException $e) {
+            if (!$skipErrors) {
+                throw $e;
+            }
+            $output->writeln(sprintf('<warning>%s: %s</warning>', get_class($e), $e->getMessage()));
         }

         if ($repositoryUrl !== null && count($packagesFilter) > 0) {
```

**Comment by alcohol** [comment]
That's fine with me too, I was just pointing out this change :-)

**Comment by glensc** [comment]
added, can it be merged now?

**Pull request merged**
