### PR TITLE
Add anchor link on package name

### PR DESCRIPTION
**Pull request by jdeniau**

### CODE REVIEW

**Comment by jdeniau** [comment]
:up:

**Comment by joshdifabio** [comment]
Sweet! Is it possible that the package name can contain special URL characters (and need escaping)?

**Comment by jdeniau** [comment]
I don't think so

**Comment by stof** [comment]
package names are restricted in ``composer validate``, so it should be fine

**Comment by alcohol** [comment]
If you could update this PR, I will gladly merge it.

**Comment by alcohol** [comment]
This PR is in a conflicting state. Do you wish to update it, or can it be closed?

**Comment by jdeniau** [comment]
Replaced by #302

**Pull request closed without merging**
