### PR TITLE
Include replacing packages into package providers (#367)

### PR DESCRIPTION
**Pull request by copitz**
Please see #367 for a detailed explanation on what this change fixes

### CODE REVIEW

**Comment by alcohol** [comment]
Thanks

**Comment by stof** [comment]
this is missing support for ``provide`` though

**Comment by copitz** [comment]
You're right - the thing is that I didn't know how to reflect provided packages in the provider includes. If s.o. could help me figuring this out, we/I could handle this in a new issue...

**Comment by stof** [comment]
@copitz hmm, Packagist indeed does not dump a provider file for packages which are only provided. But this looks like a bug in Packagist IMO, as it means that composer will not be able to find packages providing ``psr/http-message-implementation`` for instance

**Pull request merged**
