### PR TITLE
Fixed the purge command.

### PR DESCRIPTION
**Pull request by Adirelle**
The purge command now extracts a strict list of files to keep from the JSON packages and removes all non-matching files from the archive directory. See #331.

### CODE REVIEW

**Comment by alcohol** [comment]
Would it not be better to make this behaviour a flag on the `purge` command? I can imagine that someone might want the purge command to remove everything?

**Comment by Adirelle** [comment]
> I can imagine that someone might want the purge command to remove everything?

There is `rm` for those cases.

**Comment by alcohol** [comment]
Thanks.

**Pull request merged**
