### PR TITLE
dont render repo-config in initial view

### LINKED ISSUE #504: streamline the UI
the satis web UI uses a lot of room for the "repository-config" section. this information is only required on the initial setup of your composer workflow.

IMO we could e.g. collapse this area by default and expand it on click of the `Add this Satis repository to your composer.json` label.

bottom-line: the most important information - the package-list and its releases - do not use the most space of the website (above the fold).

wdyt?

### PR DESCRIPTION
**Pull request by staabm**
closes #504 

*BEFORE*

grafik

*AFTER*
- initial state

grafik

- after click on `Add this Satis repository to your composer.json`

grafik

### CODE REVIEW

**Comment by alcohol** [comment]
Conflict :-(

**Comment by staabm** [comment]
resolved

**Comment by alcohol** [comment]
Odd, Github UI still shows it as conflicting.

**Comment by alcohol** [comment]
Oh never mind, it is because I always use rebase and merge, and you did not rebase your branch.

I can squash and merge instead.

**Pull request merged**
