### PR TITLE
Add commands which help manage configuration file

### PR DESCRIPTION
**Pull request by skolodyazhnyy**
Hi,

I have added few commands to help get started with satis. 

- `satis init [config-file]` - allows to generate basic satis configuration file
- `satis add <repository-url> [config-file]` - adds repository URL to the configuration file

### CODE REVIEW

**Comment by skolodyazhnyy** [comment]
Any chance to get it merged?

**Comment by gillesodret** [comment]
Hi,

I wrote some code to do things like this for a similar project, aimed to depend on satis but with its own life. I put two classes online at @holisticagency

* a satis file manager, dealing with the same purpose of this PR,
* a dedicated http client.

i'll soon release a full CLI tool using these classes that will be able to build and push repositories on private, static web repositories.

the idea is to handle such repositories with a per-project approach.

I don't know if it is the right place to talk about it, sorry in advance if it is inappropriate...

**Comment by alcohol** [comment]
@skolodyazhnyy any chance you can confirm it still works with all the recent changes/merges? If so, I will gladly merge it.

**Comment by skolodyazhnyy** [comment]
@alcohol I will have a look today and let you know. Thanks for coming back.

**Comment by skolodyazhnyy** [comment]
@alcohol I've created a new fork and applied changes there. It still works fine, you can merge this PR if you find it useful.

**Pull request merged**
