### PR TITLE
split dist files per vendor and package

### LINKED ISSUE #68: dist files could follow the composer cache organization
For the sake of clarity, and to match the composer cache, dist files could be relocated to something like `output-dir/directory/vendor-name/bundle-name/`

The vendor and bundle parts could also be dropped in the file name .

### PR DESCRIPTION
**Pull request by alcohol**
closes #68

implementation is kind of cringe-worthy, but so is most of the codebase unfortunately, so not sure if worth investing more effort

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by alcohol** [comment]
I tested it quickly with a very basic satis configuration. Worked as expected, but no idea if there might be edge-cases.

**Comment by aaukt** [comment]
Correct me if i'm wrong, but i think it should be noted that people should be cautious with rolling this out to existing satis repositories, because the old paths are still in the composer.lock.

So either do not delete the old archives or put some clever redirect logic in place.

**Comment by alcohol** [comment]
Nothing gets deleted by default. Deletions only happen when you run the purge command.

**Comment by aaukt** [comment]
I know, just if you wonder why you should keep a duplicate of all archives.

**Pull request merged**
