### PR TITLE
Clean up .prettierignore, update dependencies

### PR DESCRIPTION
**Pull request by theimbender**
- Clean up the entries in `.prettierignore` so that only generated files should be ignored
- Update npm/composer dependencies to latest
- Remove `.gitignore` from `.husky` directory, that's not needed in latest version of husky
- Updated readme link that still pointed to license file on master branch

### CODE REVIEW

**Comment by theimbender** [comment]
Should we be running `composer update` on php 8.1 or 7.3? I was running it on 7.3 and got some downgraded dependencies, isn't that desirable since it's the minimum supported version?

**Comment by theimbender** [comment]
Seems to be the same issues as #690, I think we'd want to only commit lock files generated with the minimum supported version of php

**Comment by alcohol** [comment]
Yeah I am not sure. Personally I would rather only support the latest versions of PHP. But Satis is a community product. If the community feels a need to support older version(s), then we should pin the PHP configuration to the lowest supported version in the `composer.json` file. That way, no mater what environment you run `composer update` on, the configured PHP version will be leading.

**Comment by theimbender** [comment]
This should be good to merge now, I think, now that the composer lock file has been rebased

**Pull request merged**
