### PR TITLE
[Issue #374] Added row for displaying package requirements 

### PR DESCRIPTION
**Pull request by mooror**
I went ahead and implemented the requirements row. Now I found that my version of satis is an older one so I actually had to adapt this code for my installation. I have not tested this code with the new version and therefor cannot confirm that it works. My hope is that it either works without issue or will give you a bit of a head start.

Hope it helps a bit,
Mooror

P.S. For the record, I really enjoy what satis does but I find the name rather unsettling.

### CODE REVIEW

**Comment by alcohol** [comment]
I tried it out, but I am not sure this adds much value. It attempts to link to anchors on the same page that do not necessarily exist. Nor is it possible to determine which constraints apply. Also, the requirements might not actually apply to all listed versions.

satis

**Comment by mooror** [comment]
I was aware of the problem with the links but I had overlooked the second problem you mentioned...For the first issue I guess we could just forgo the <a> tags all together and just list the items as direct children of the <li> tags.

**Comment by mooror** [comment]
I am curious as to how my requirements row differs from the concept behind the "Required By" row. I might have missed it in the code, but I don't recall seeing version handling for that row either. If this is indeed the case then I would argue that just as the "Required By" row lets the developer see packages that rely on the item, regardless of the version; my row lets the developer know that one of the versions of the item relies on packages in the list.

Looking forward to more discussion,
Mooror

P.S. Sorry if my post is a bit confusing

**Comment by mooror** [comment]
As I discovered in issue #376, my requirements row implementation seems to be unreliable. Unfortunately I don't have time to look into this more but I would definitely recommend that someone do a full test on my code before thinking about merging it.

Sorry for the let down,
Mooror

**Pull request closed without merging**
