### PR TITLE
Add an abandoned config key to mark packages as so

### LINKED ISSUE #183: Satis should allow defining abandoned packages like packagist
The equivalent of https://github.com/composer/packagist/issues/192 in satis.json

### PR DESCRIPTION
**Pull request by atimmer**
Fixes #183, #213.

I chose the straightforward approach, just a new config option with key value pairs to define abandonment of packages. Let me know if this is the correct approach.

### CODE REVIEW

**Comment by fabiang** [comment]
:+1:

**Comment by shochdoerfer** [comment]
:+1:

**Comment by patkar** [comment]
:+1:

**Comment by jaapio** [comment]
+1

**Comment by alcohol** [comment]
@atimmer if you could rebase this, I'll get it merged :)

**Pull request closed without merging**
