### PR TITLE
Update only one package

### PR DESCRIPTION
**Pull request by kpitn**
Actually you can't update only one package. (See this discussion #40)

With this PR you can select one package to update.

You need to define your json schema with a new "name" node  : 
```json
    "repositories": [
        {
            "name": "package_name",
            "type": "vcs",
            "url":  "git@bitbucket.org:team/package_name.git"
        },
```
Now you can execute this query : 

`bin/satis build my-schema.json my-webroot my_package_name`

### CODE REVIEW

**Comment by alcohol** [comment]
Would be great if you could include a test.

**Comment by alcohol** [comment]
Maybe it should be pointed out / documented that this only works for VCS type repositories

**Comment by alcohol** [comment]
The satis.json schema should also be updated ([satis-schema.json](https://github.com/composer/satis/blob/master/res/satis-schema.json)).

**Comment by alcohol** [comment]
@kpitn Can you update/rebase this PR? Otherwise I'll close it in a while.

**Comment by kpitn** [comment]
I try to rebase and push, but I think it's already up to date.
I made a PR in the documentation here :  https://github.com/composer/composer/pull/8215

**Comment by alcohol** [comment]
Sorry, I should have been more clear perhaps. Documentation should be kept up to date in this repository. Once it is finished, we actually want to remove it from the documentation in the Composer repository.

**Comment by kpitn** [comment]
Ok do you have a PR or branch with documentation up to date ?

Actually i see the page is empty : https://github.com/composer/satis/blob/master/docs/using.md

**Comment by alcohol** [comment]
It is a work in progress.

**Comment by glensc** [comment]
you don't need to create new PR just to rebase; just rebase and `git push -f`.

as I see you did merge here, not rebase, therefore it shows merged commits also as part of the PR.

**Pull request closed without merging**
